require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DeclarationsController do

  # This should return the minimal set of attributes required to create a valid
  # Declaration. As you add validations to Declaration, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all declarations as @declarations" do
      declaration = Declaration.create! valid_attributes
      get :index
      assigns(:declarations).should eq([declaration])
    end
  end

  describe "GET show" do
    it "assigns the requested declaration as @declaration" do
      declaration = Declaration.create! valid_attributes
      get :show, :id => declaration.id.to_s
      assigns(:declaration).should eq(declaration)
    end
  end

  describe "GET new" do
    it "assigns a new declaration as @declaration" do
      get :new
      assigns(:declaration).should be_a_new(Declaration)
    end
  end

  describe "GET edit" do
    it "assigns the requested declaration as @declaration" do
      declaration = Declaration.create! valid_attributes
      get :edit, :id => declaration.id.to_s
      assigns(:declaration).should eq(declaration)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Declaration" do
        expect {
          post :create, :declaration => valid_attributes
        }.to change(Declaration, :count).by(1)
      end

      it "assigns a newly created declaration as @declaration" do
        post :create, :declaration => valid_attributes
        assigns(:declaration).should be_a(Declaration)
        assigns(:declaration).should be_persisted
      end

      it "redirects to the created declaration" do
        post :create, :declaration => valid_attributes
        response.should redirect_to(Declaration.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved declaration as @declaration" do
        # Trigger the behavior that occurs when invalid params are submitted
        Declaration.any_instance.stub(:save).and_return(false)
        post :create, :declaration => {}
        assigns(:declaration).should be_a_new(Declaration)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Declaration.any_instance.stub(:save).and_return(false)
        post :create, :declaration => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested declaration" do
        declaration = Declaration.create! valid_attributes
        # Assuming there are no other declarations in the database, this
        # specifies that the Declaration created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Declaration.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => declaration.id, :declaration => {'these' => 'params'}
      end

      it "assigns the requested declaration as @declaration" do
        declaration = Declaration.create! valid_attributes
        put :update, :id => declaration.id, :declaration => valid_attributes
        assigns(:declaration).should eq(declaration)
      end

      it "redirects to the declaration" do
        declaration = Declaration.create! valid_attributes
        put :update, :id => declaration.id, :declaration => valid_attributes
        response.should redirect_to(declaration)
      end
    end

    describe "with invalid params" do
      it "assigns the declaration as @declaration" do
        declaration = Declaration.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Declaration.any_instance.stub(:save).and_return(false)
        put :update, :id => declaration.id.to_s, :declaration => {}
        assigns(:declaration).should eq(declaration)
      end

      it "re-renders the 'edit' template" do
        declaration = Declaration.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Declaration.any_instance.stub(:save).and_return(false)
        put :update, :id => declaration.id.to_s, :declaration => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested declaration" do
      declaration = Declaration.create! valid_attributes
      expect {
        delete :destroy, :id => declaration.id.to_s
      }.to change(Declaration, :count).by(-1)
    end

    it "redirects to the declarations list" do
      declaration = Declaration.create! valid_attributes
      delete :destroy, :id => declaration.id.to_s
      response.should redirect_to(declarations_url)
    end
  end

end
