require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DeclaredRealEstatesController do

  # This should return the minimal set of attributes required to create a valid
  # DeclaredRealEstate. As you add validations to DeclaredRealEstate, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all declared_real_estates as @declared_real_estates" do
      declared_real_estate = DeclaredRealEstate.create! valid_attributes
      get :index
      assigns(:declared_real_estates).should eq([declared_real_estate])
    end
  end

  describe "GET show" do
    it "assigns the requested declared_real_estate as @declared_real_estate" do
      declared_real_estate = DeclaredRealEstate.create! valid_attributes
      get :show, :id => declared_real_estate.id.to_s
      assigns(:declared_real_estate).should eq(declared_real_estate)
    end
  end

  describe "GET new" do
    it "assigns a new declared_real_estate as @declared_real_estate" do
      get :new
      assigns(:declared_real_estate).should be_a_new(DeclaredRealEstate)
    end
  end

  describe "GET edit" do
    it "assigns the requested declared_real_estate as @declared_real_estate" do
      declared_real_estate = DeclaredRealEstate.create! valid_attributes
      get :edit, :id => declared_real_estate.id.to_s
      assigns(:declared_real_estate).should eq(declared_real_estate)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DeclaredRealEstate" do
        expect {
          post :create, :declared_real_estate => valid_attributes
        }.to change(DeclaredRealEstate, :count).by(1)
      end

      it "assigns a newly created declared_real_estate as @declared_real_estate" do
        post :create, :declared_real_estate => valid_attributes
        assigns(:declared_real_estate).should be_a(DeclaredRealEstate)
        assigns(:declared_real_estate).should be_persisted
      end

      it "redirects to the created declared_real_estate" do
        post :create, :declared_real_estate => valid_attributes
        response.should redirect_to(DeclaredRealEstate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved declared_real_estate as @declared_real_estate" do
        # Trigger the behavior that occurs when invalid params are submitted
        DeclaredRealEstate.any_instance.stub(:save).and_return(false)
        post :create, :declared_real_estate => {}
        assigns(:declared_real_estate).should be_a_new(DeclaredRealEstate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DeclaredRealEstate.any_instance.stub(:save).and_return(false)
        post :create, :declared_real_estate => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested declared_real_estate" do
        declared_real_estate = DeclaredRealEstate.create! valid_attributes
        # Assuming there are no other declared_real_estates in the database, this
        # specifies that the DeclaredRealEstate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DeclaredRealEstate.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => declared_real_estate.id, :declared_real_estate => {'these' => 'params'}
      end

      it "assigns the requested declared_real_estate as @declared_real_estate" do
        declared_real_estate = DeclaredRealEstate.create! valid_attributes
        put :update, :id => declared_real_estate.id, :declared_real_estate => valid_attributes
        assigns(:declared_real_estate).should eq(declared_real_estate)
      end

      it "redirects to the declared_real_estate" do
        declared_real_estate = DeclaredRealEstate.create! valid_attributes
        put :update, :id => declared_real_estate.id, :declared_real_estate => valid_attributes
        response.should redirect_to(declared_real_estate)
      end
    end

    describe "with invalid params" do
      it "assigns the declared_real_estate as @declared_real_estate" do
        declared_real_estate = DeclaredRealEstate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DeclaredRealEstate.any_instance.stub(:save).and_return(false)
        put :update, :id => declared_real_estate.id.to_s, :declared_real_estate => {}
        assigns(:declared_real_estate).should eq(declared_real_estate)
      end

      it "re-renders the 'edit' template" do
        declared_real_estate = DeclaredRealEstate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DeclaredRealEstate.any_instance.stub(:save).and_return(false)
        put :update, :id => declared_real_estate.id.to_s, :declared_real_estate => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested declared_real_estate" do
      declared_real_estate = DeclaredRealEstate.create! valid_attributes
      expect {
        delete :destroy, :id => declared_real_estate.id.to_s
      }.to change(DeclaredRealEstate, :count).by(-1)
    end

    it "redirects to the declared_real_estates list" do
      declared_real_estate = DeclaredRealEstate.create! valid_attributes
      delete :destroy, :id => declared_real_estate.id.to_s
      response.should redirect_to(declared_real_estates_url)
    end
  end

end
