require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OfficeTypesController do

  # This should return the minimal set of attributes required to create a valid
  # OfficeType. As you add validations to OfficeType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all office_types as @office_types" do
      office_type = OfficeType.create! valid_attributes
      get :index
      assigns(:office_types).should eq([office_type])
    end
  end

  describe "GET show" do
    it "assigns the requested office_type as @office_type" do
      office_type = OfficeType.create! valid_attributes
      get :show, :id => office_type.id.to_s
      assigns(:office_type).should eq(office_type)
    end
  end

  describe "GET new" do
    it "assigns a new office_type as @office_type" do
      get :new
      assigns(:office_type).should be_a_new(OfficeType)
    end
  end

  describe "GET edit" do
    it "assigns the requested office_type as @office_type" do
      office_type = OfficeType.create! valid_attributes
      get :edit, :id => office_type.id.to_s
      assigns(:office_type).should eq(office_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OfficeType" do
        expect {
          post :create, :office_type => valid_attributes
        }.to change(OfficeType, :count).by(1)
      end

      it "assigns a newly created office_type as @office_type" do
        post :create, :office_type => valid_attributes
        assigns(:office_type).should be_a(OfficeType)
        assigns(:office_type).should be_persisted
      end

      it "redirects to the created office_type" do
        post :create, :office_type => valid_attributes
        response.should redirect_to(OfficeType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved office_type as @office_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        OfficeType.any_instance.stub(:save).and_return(false)
        post :create, :office_type => {}
        assigns(:office_type).should be_a_new(OfficeType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OfficeType.any_instance.stub(:save).and_return(false)
        post :create, :office_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested office_type" do
        office_type = OfficeType.create! valid_attributes
        # Assuming there are no other office_types in the database, this
        # specifies that the OfficeType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        OfficeType.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => office_type.id, :office_type => {'these' => 'params'}
      end

      it "assigns the requested office_type as @office_type" do
        office_type = OfficeType.create! valid_attributes
        put :update, :id => office_type.id, :office_type => valid_attributes
        assigns(:office_type).should eq(office_type)
      end

      it "redirects to the office_type" do
        office_type = OfficeType.create! valid_attributes
        put :update, :id => office_type.id, :office_type => valid_attributes
        response.should redirect_to(office_type)
      end
    end

    describe "with invalid params" do
      it "assigns the office_type as @office_type" do
        office_type = OfficeType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OfficeType.any_instance.stub(:save).and_return(false)
        put :update, :id => office_type.id.to_s, :office_type => {}
        assigns(:office_type).should eq(office_type)
      end

      it "re-renders the 'edit' template" do
        office_type = OfficeType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OfficeType.any_instance.stub(:save).and_return(false)
        put :update, :id => office_type.id.to_s, :office_type => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested office_type" do
      office_type = OfficeType.create! valid_attributes
      expect {
        delete :destroy, :id => office_type.id.to_s
      }.to change(OfficeType, :count).by(-1)
    end

    it "redirects to the office_types list" do
      office_type = OfficeType.create! valid_attributes
      delete :destroy, :id => office_type.id.to_s
      response.should redirect_to(office_types_url)
    end
  end

end
